// Generated by CoffeeScript 1.9.2
var extend;

extend = require('extend');

module.exports = function(initialState) {
  var _layers, _state;
  _state = {};
  _layers = [];
  if (initialState != null) {
    extend(_state, initialState);
  }
  return {
    apply: function(diff) {
      return extend(_state, diff);
    },
    _state: function() {
      return _state;
    },
    clear: function() {
      return _state = {};
    },
    get: function() {
      var i, layer, len, result;
      result = {};
      extend(result, _state);
      for (i = 0, len = _layers.length; i < len; i++) {
        layer = _layers[i];
        extend(result, layer);
      }
      return result;
    },
    layer: function(layer) {
      _layers.push(layer);
      return {
        rollback: function() {
          var index;
          index = _layers.indexOf(layer);
          return _layers.splice(index, 1);
        },
        commit: function() {
          var index;
          index = _layers.indexOf(layer);
          _layers.splice(index, 1);
          return extend(_state, layer);
        }
      };
    }
  };
};
